import { jsPDF } from 'jspdf';

export function downloadReceipt(reservation) {
  const doc = new jsPDF();
  const now = new Date().toLocaleString();

  doc.setFillColor(14, 165, 233);
  doc.rect(0, 0, 210, 34, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.text('New Beach Oran', 18, 16);
  doc.setFontSize(11);
  doc.text('Three Worlds In One Place', 18, 25);

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(18);
  doc.text(`Reservation Code: ${reservation.code}`, 18, 50);

  let y = 66;
  const row = (label, value) => {
    doc.setFont('helvetica', 'bold');
    doc.text(`${label}:`, 18, y);
    doc.setFont('helvetica', 'normal');
    doc.text(String(value || '-'), 74, y);
    y += 10;
  };

  row('Full Name', reservation.fullName);
  row('Email', reservation.email);
  row('Phone', reservation.phone || '-');
  row('Zone', reservation.zone.name);
  row('Seat Type', reservation.seatType);
  row('People', reservation.people);
  row('Date', reservation.date);
  row('Unit Price', `${reservation.unitPrice.toLocaleString('en-US')} DA`);
  row('Total', `${reservation.unitPrice.toLocaleString('en-US')} x ${reservation.people} = ${reservation.total.toLocaleString('en-US')} DA`);
  row('Payment', reservation.paymentMethod === 'online' || reservation.paid ? 'Paid Online via Chargily' : 'Cash on Arrival');

  y += 8;
  doc.setFillColor(248, 250, 255);
  doc.roundedRect(18, y, 174, 36, 4, 4, 'F');
  doc.setFont('helvetica', 'bold');
  doc.text('Beach Contact', 26, y + 11);
  doc.setFont('helvetica', 'normal');
  doc.text('Instagram: @costafiestabynb', 26, y + 21);
  doc.text('Phone: 0560 33 79 91 | Email: costafiesta748@gmail.com', 26, y + 30);
  doc.text('Facebook: Costa Fiesta By Plaza New Beach', 26, y + 39);

  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(`Receipt generated by New Beach Oran Booking System - ${now}`, 18, 286);
  doc.save(`${reservation.code}-receipt.pdf`);
}
